name: CI
permissions:
  contents: read
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22.14.0
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          # github secrets through preview environment
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun
